### ISSUE TITLE
NO-CHANGE

### ISSUE THREAD

**Issue by wazzer007** [VandalByte/dedsec-grub2-theme#15]
HI GUYS
I used python script to install provided by you thankfully it went correctly but once i 
sudo grub-mkconfig -o /boot/grub/grub.cfg typed this it say`s following:

"Generating grub configuration file ...
Found theme: /boot/grub/themes/kali/theme.txt
Found background image: /usr/share/images/desktop-base/desktop-grub.png
Found linux image: /boot/vmlinuz-5.17.0-kali3-amd64
Found initrd image: /boot/initrd.img-5.17.0-kali3-amd64
Found linux image: /boot/vmlinuz-5.16.0-kali7-amd64
Found initrd image: /boot/initrd.img-5.16.0-kali7-amd64
Warning: os-prober will not be executed to detect other bootable partitions.
Systems on them will not be added to the GRUB boot configuration.
Check GRUB_DISABLE_OS_PROBER documentation entry.
Adding boot menu entry for UEFI Firmware Settings ...
done"

I`m Curious Does This Changes Boot Loader Because of this "Found theme: 
 boot/grub/themes/kali/theme.txt"

And I think I need help for these: >>>

Warning: os-prober will not be executed to detect other bootable partitions.
Systems on them will not be added to the GRUB boot configuration.
Check GRUB_DISABLE_OS_PROBER documentation entry.

And thanks for the help !!!!

**Comment by VandalByte** [comment]
Hey @wazzer007 

>I`m Curious Does This Changes Boot Loader Because of this "Found theme:
boot/grub/themes/kali/theme.txt"

Like most other distros Kali doesn't allow you to change the grub theme out of the box, it needs a little bit tweaking . Check out this [doc](https://github.com/VandalByte/grub-tweaks#-setting-up-grub-theme-in-kali-linux) that I wrote, that should fix it ;)

> Warning: os-prober will not be executed to detect other bootable partitions.
Systems on them will not be added to the GRUB boot configuration.
Check GRUB_DISABLE_OS_PROBER documentation entry.

And now for this, `os-prober` has been disabled by default, you need to uncomment/add
```
GRUB_DISABLE_OS_PROBER=false
```
to `/etc/default/grub` and run `sudo update-grub`

**Comment by wazzer007** [comment]
worked thanks
