### ISSUE TITLE
Command lsb_released -i issue

### ISSUE THREAD

**Issue by flazz01** [VandalByte/dedsec-grub2-theme#17]
I am encountered this ERROR, what does it mean?

![Screenshot from 2022-07-10 09-12-25](https://user-images.githubusercontent.com/73412961/178128617-fbe8b4c9-0fd3-4b97-bb14-a680e53f9047.png)

**Comment by VandalByte** [comment]
Hey @flazz01 , It's actually a part of the script that checks to see if it's a Kali Linux distro and, if so, displays an additional message to those users. This worked for me on Endeavor OS, Kali and Fedora. However, it appears that the command is not installed on your system.

You can ignore that error, the theme should be properly installed, however, could you please tell me which distro you are using?

**Comment by flazz01** [comment]
> Hey @flazz01 , It's actually a part of the script that checks to see if it's a Kali Linux distro and, if so, displays an additional message to those users. This worked for me on Endeavor OS, Kali and Fedora. However, it appears that the command is not installed on your system.
> 
> You can ignore that error, the theme should be properly installed, however, could you please tell me which distro you are using?

Im using fedora 36. You are right even i got this error, grub theme was perfectly installed.

Thank you for your explanation dev.
