### ISSUE TITLE
Failure to install from Aur

### ISSUE THREAD

**Issue by d4rios** [VandalByte/dedsec-grub2-theme#23]
When trying to install the package with yay from Aur I get the following error message: "_install: unable to perform `stat' on '/home/d4riu5/.cache/yay/dedsec-grub2-theme/src/dedsec-grub2-theme/assets/backgrounds/compact.png': file or directory does not exist"

**Comment by VandalByte** [comment]
As the author, I have not officially added this project to AUR, but it may have been added by someone else. I would recommend installing it from the official repository here rather than from there, as it is more likely that the version on the other repository may be outdated
