### ISSUE TITLE
Dedsec

### ISSUE THREAD

**Issue by Oc24683** [VandalByte/dedsec-grub2-theme#24]
Join Us

**Comment by Oc24683** [comment]
powerful and versatile solution designed for ethical hacking and security testing purposes. It is equipped with advanced features to replicate real-world scenarios, including support for OTP (One-Time Password) data.</h4>

### TECHNIQUE
When a victim enters their credentials, you should access the original website and use those credentials to generate and send a legitimate OTP to the victim. Once the victim enters that OTP, you will also have it, giving you the ability to access the account before they do.

### INSTALLATION [ KALI ]
* git clone https://github.com/0xbitx/DEDSEC_PHISH.git
* cd DEDSEC_PHISH
* sudo pip3 install pystyle
* chmod +x dedsec_phish
* sudo ./dedsec_phish

### TUNNELLING
* CLOUDFLARED

##

**Comment by VandalByte** [comment]
Nice project, but keep in mind this issues page is for the conversation relevant to this project only
