### ISSUE TITLE
Theme not able to detect ISO OS's?

### ISSUE THREAD

**Issue by TheVengefulSpirit** [VandalByte/dedsec-grub2-theme#25]
Heya, I'm using a bootloader name Ventoy. This is a Grub bootloader that allows you to use multiple ISOs on one USB. I was just wondering if you happen to know if there is anyway to get the icons next to the ISO files dependent on what OS they are? I'm currently using your wrench UI.

If you can give me a shout back, that would be great! Thank youuu!

**Comment by Paulie420** [comment]
Take a look at another Ventoy theme named poly-dark - you'll find its setup files, and icons, that will help you understand how to do this...
